name: Smite
main: me.comp.Smite.Smite
version: 5.0
description: >
             My first smiting plugin.
commands:
  smite:
    description: Lightning
  smitekill:
    description: kills a player

permissions:
    smite.ground:
        description: Allows you to hit the ground
        default: op
    smite.player:
        description: Allows you to hit a player
        default: op